### PR TITLE
Build for Scala 2.11

### PR DESCRIPTION
**Pull request by ccw**
- Upgraded Scala version to 2.11
 - Upgraded dependency to newer version
 - Removed the explicit sbt version 
 - Reformat code and as well refined some out-dated syntax
 - Changed the TestAgent to be listening on port 1234 to prevent permission denied exception on Linux

### CODE REVIEW

**Comment by joescii** [comment]
So... wow.... I had no idea anyone cared about this old project that I played around with. :)

Why do you prefer to remove the explicit sbt version? I've always felt this is best practice.

**Comment by ccw** [comment]
Thanks for having this project available. We are testing on SNMP with our internal Scala systems and this project looks perfectly meet our needs as long as it can be 2.11 compliance. :)

Yes, I think you're right. It is better to explicitly specify the sbt version in most of the cases. I originally wanted to remove it was because we internally prefer to use the latest sbt. If we explicit the version, we will then have to modify the properties file accordingly every time.

**Comment by Kunjin** [comment]
This project is very helpful to me. 
Joescii, Could you update this pull request and update new version to the [maven repository website](http://search.maven.org/#search%7Cga%7C1%7Csnmp4s).
Thank you very much.

**Comment by joescii** [comment]
Did you run tests on all of the sub projects? I get an error in the `gen` project.

**Comment by ccw** [comment]
@joescii two additional fixes have been added, one is to fix the test compile error you have mentioned and the other is to allow not providing the `src/main/mibs` folder while only the default MIBs needed to be generated.

**Comment by joescii** [comment]
I noticed that the `gen` and `sbt` projects are still building for `2.10`. Do you not use either of those?

**Comment by ccw** [comment]
@joescii it is because the build tool `sbt` itself can only be built with `2.10` so as its plugins.

**Comment by joescii** [comment]
Geez, I'm an idiot.

**Comment by joescii** [comment]
@ccw Ok, seems like everything works as expected now. Not really sure what went wrong with the `gen` project considering you hadn't needed to touch it, lol.

But before I pull the trigger on publishing `0.2.0`, you _are_ aware that there are changes I made since `0.1.0`, right? Just want to make sure that this `0.2.0` version is exactly what you're looking for. I have no idea what those changes were made for considering it has been years since I've looked at this code.

**Comment by ccw** [comment]
@joescii yes, and we very appreciate your work which helps us a lot. :smile:

**Comment by joescii** [comment]
Y'all let me know if you have any problems with the release. Thanks for fixing it up!

**Comment by ccw** [comment]
Thanks.

BTW, could you also help us to publish to central maven repo? Very appreciated.

**Pull request merged**
